# =========================================================
# YAIF R2S Network Optimization
#
# TCP BBR
#
# =========================================================

net.core.default_qdisc=fq

net.ipv4.tcp_congestion_control=bbr

