# =========================================================
# YAIF R2S Network Optimization
#
# TCP BBR
#
# =========================================================

net.core.default_qdisc = fq_codel
net.ipv4.tcp_congestion_control = bbr

# 网络响应与协议优化
net.ipv4.tcp_ecn = 0
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_tw_reuse = 1

# 高并发连接优化
net.core.somaxconn = 4096
net.ipv4.tcp_max_syn_backlog = 4096

# 连接跟踪
net.netfilter.nf_conntrack_max = 65536